version: "3.8"

services:
  # Backend Service
  backend:
    image: ${DOCKERHUB_USERNAME}/prompthub-backend:latest
    container_name: prompthub-backend
    restart: always
    env_file:
      - ./backend/.env.production
    ports:
      - "4000:4000"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').request('http://localhost:4000/.well-known/apollo/server-health', console.log).end()",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend Service
  frontend:
    image: ${DOCKERHUB_USERNAME}/prompthub-frontend:latest
    container_name: prompthub-frontend
    restart: always
    env_file:
      - ./frontend/.env.production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').request('http://localhost:3000', console.log).end()"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: prompthub-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
